wasm-tool/wasm-pack-plugin

- example/README.md
- example/package.json
- loader.js
I've unified the path so it can work well also in Windows.
On the other hand, `http-server` wasn't working because some issues with Windows and MIME types so I've changed the dependency to one working in all operating systems (`local-web-server`).
Finally, I've updated the example's README.
> fix(OS): support for windows

- plugin.js
> Use `wasm-pack init` instead of `build`

- README.md
- example/webpack.config.js
- plugin.js
Add a `withTypescript` option to optionally generate `d.ts` files for the wasm module in order to integrate with typescript.
Example `tsconfig.json`
```js
{
"compilerOptions": {
"module": "esnext", // needed to have dynamic imports
"lib": [
"dom",
"es2015"
]
},
"files": [
"./index.ts"
]
}
```
Example `webpack.config.json`
```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const WasmPackPlugin = require("@wasm-tool/wasm-pack-plugin");
module.exports = {
entry: "./index.ts",
output: {
path: path.resolve(__dirname, "dist"),
filename: "bundle.js"
},
plugins: [
new HtmlWebpackPlugin(),
new WasmPackPlugin({
crateDirectory: path.resolve(__dirname, "."),
withTypeScript: true
}),
],
resolve: {
extensions: [".ts", ".tsx", ".js", ".wasm"]
},
module: { …
```
> add withTypescript option

- plugin.js
This is important so crucial env variables like CARGO_HOME are preserved properly.
Fixes issue #39
> Keep the environment of the parent process intact

- README.md
- plugin.js
Sometimes, inheriting the webpack compiler's watch mode isn't exactly what we want when building a dependency with `wasm-pack`. (As an example, many advanced HMR implementations set up a separate watcher for changes in certain directories and implement a custom watcher, such as the one used in `electron-webpack`.)
For my project, it's very helpful to be able to watch `.rs` files on-demand, regardless of if the `webpack` watcher is on. I thought perhaps an option that turns "watch mode" on and off (which is a noop deferring to `webpack` if not specified) would make the most sense for this, but please let me know if you have a better idea!
> Allow configure-time watch mode for wasm-pack independent of webpack.

- plugin.js
The compiler is not initialized when the check is happening. Moving this inside the hook, ensures that the compiler is actually initialized correctly with default values.
Locally it works.
Closes #43 
r? @xtuc  {Probably release a version once it is merged}
> fix: watch for files

- package.json
- plugin.js
**Problem:** The watcher is set up only once during the initial compilation (because of `ranInitialCompilation` flag) and thus won't pick up any new/renamed files inside the crate's `src/` dir.
**Solution:** Set up the watcher to monitor the `src/` dir instead of individual `*.rs` files.
> Watch `src` dir instead of individual files

- README.md
- plugin.js
**Problem:** Currently the watcher is set up to monitor only the main crate's `src/` directory and in case you're working on a few interdependent packages at the same time, there's no way to trigger build on changes to any of the secondary crates.
**Solution:** Allow customizing the directory watch list.
> Configurable watch list

- package.json
- plugin.js
Closes #49 and bumps the version to `0.2.2`
> fix for when multiple configs are exported

- plugin.js
This is a 1-line change to avoid errors like this:
Since this is a very small change I didn't bump the version number in case you wanted to include this in a larger release.
> added error listener

- plugin.js
Refs https://github.com/rustwasm/rust-webpack-template/issues/116
The `wasm-pack` tool [builds in release mode by default](https://rustwasm.github.io/wasm-pack/book/commands/build.html#profile), so when the wasm-pack-plugin defaults to development mode it can be confusing for uses (see https://github.com/rustwasm/rust-webpack-template/issues/116).
This adds a message so that the console will clearly display when the crate is being compiled in development mode.
> Add message indicating when crate is compiled in development mode

- plugin.js
Looks like in the [`v0.6.0`](https://github.com/rustwasm/wasm-pack/releases/tag/v0.6.0) release the `--debug` flag was deprecated in favor of `--dev`.
> Use build flag "--dev" instead of "--debug"

- package.json
- plugin.d.ts
This PR adds a simple TypeScript declaration file to allow this module to be used in TypeScript projects with type-safety. I just based it off the documentation in the README, but it's been good enough for me in local projects.
> Add Type Declarations for Webpack configurations written in TypeScript.

- README.md
Hi, developers.
The installation link, <https://github.com/rustwasm/wasm-pack/blob/master/docs/src/setup.md#installing-wasm-pack> is "Page not found". So, I replace it with <https://rustwasm.github.io/wasm-pack/installer/>.
> docs: fix installation link

- plugin.d.ts
Missing `outDir` and `outName` in `plugin.d.ts`
> ts: declare outDir and outName in options

- README.md
- plugin.d.ts
- plugin.js
Allow wasm-pack command line parameters to be specified and passed. When
unspecified, continue to default to `--verbose` to avoid a breaking
change.
fix #79
> [feature] allow pre-command arguments to be passed

- README.md
- plugin.d.ts
- plugin.js
Allow wasm-pack-plugin's output level to controlled via a new
configuration, pluginLogLevel. Valid values are 'info' (the default) or
'error'. The former maintains the status quo and the latter only reports
serious errors.
The rationale for this change is that Webpack itself can be quite
verbose, to a fault even. Once the scaffolding for a wasm-pack-plugin
based project is up and running smoothly, the additional plugin's
informational messaging is less useful in combination with Webpack's
logging. This gives clients a choice in how much to log and where.
fix #83
> [feature] expose plugin logging configuration

- plugin.d.ts
As defined, this is a required config option in the TypeScript definition, but appears to be an optional config option in the actual source code.
> Make pluginLogLevel an optional config option

- plugin.d.ts
The current declaration file is written like an ambient declaration file, when it should be written as a type definition of the plugin.js (`package [main]`) file.
This makes it both useable as an ambient declaration and fixes it for normal imports.
> Fix plugin.d.ts exported type declarations

- package.json
`which` is required to run `wasm-pack-plugin`, so it must be listed as `dependencies` instead of `devDependencies`. npm/yarn don't install the devDependencies of packages, see https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies
> move which to dependencies fields

- plugin.js
Use the `'aggregated'` watch event rather than `'change'` to group together multiple changes in rapid succession, avoiding multiple simultaneous recompiles (and subsequent corruption) when using FTP or other weird file modifications.
> Switch watcher event to `aggregated` to avoid compile corruption on file changes from FTP.

- plugin.d.ts
It looks like sometime around webpack 5, the `Plugin` abstract class was renamed. There's a couple ways to patch this up, but based off internal webpack examples (like https://github.com/webpack/webpack/blob/master/types.d.ts#L163), this seems to be in line with how webpack declares their own internal plugins to match their `WebpackPluginInstance` interface.
> Update webpack type declarations for webpack 5

- plugin.js
Creates parent dirs of output directory if necessary. This makes the behavior consistent with the
rest of Webpack (for example, the `output.path` config setting creates parent dirs as needed).
> Recursively create output directory
